[package]
name = "kjhjason-blog"
version = "0.1.0"
edition = "2021"

[lints.rust]
unused_assignments = "allow"

[dependencies]
actix-web = "4.7.0"
actix-files = "0.6.6"
actix-multipart = "0.6.2"
tokio = { version = "1.38.0", features = ["full"] }
futures = "0.3.30"
futures-util = "0.3.30"
mongodb = "2.8.2"
bson = { version = "2.11.0", features = ["chrono-0_4"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
env_logger = "0.11.3"
log = "0.4.21"
derive_more = "0.99.18"
chrono = "0.4.38"
image = "0.25.1"
mime = "0.3.16"
fastuuid = "0.3.0"
dotenv = "0.15.0"
google-cloud-auth = "0.15.0"
google-cloud-storage = "0.18.0"
pulldown-cmark = "0.11.0"
hex = "0.4.3"
argon2 = "0.5.3"
rand = "0.8.5"
base64 = "0.22.1"
ring = "0.17.8"
hmac-serialiser-rs = "0.1.2"
regex = "1.10.5"
askama = "0.12.1"
askama_actix = "0.14.0"
reqwest = "0.12.4"
uuid = { version = "1.8.0", features = ["v4"] }
thiserror = "1.0.61"
minify-html = "0.15.0"
