# fly.toml app configuration file generated for kjhjason-com on 2024-06-23T23:20:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kjhjason-com'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.http_options]
    h2_backend = true

[[http_service.checks]]
  grace_period = "4s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[[vm]]
  size = 'shared-cpu-1x'
