[package]
name = "blog-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.6.0"
mongodb = "2.8.2"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
bson = "2.11.0"
pretty_env_logger = "0.5.0"
log = "0.4.21"
derive_more = "0.99.17"
chrono = "0.4.38"
